name: Update IPs
on:
  schedule:
    - cron: '*/1440 * * * *'  # هر 10 دقیقه
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resolve domain
        run: |
          DOMAIN="nima.nscl.ir"
          IP_LIST=$(dig +short $DOMAIN | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$')
          echo "$IP_LIST" > ips.txt
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ips.txt
          git commit -m "Update IPs" || echo "No changes"
          git push
